"""Add language column to Post

Revision ID: 74011c5e7d5c
Revises: b41e591b888e
Create Date: 2025-06-29 02:29:17.848740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74011c5e7d5c'
down_revision = 'b41e591b888e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
