"""Add text column to Task model

Revision ID: 7f4e9dafa494
Revises: 834b1a697901
Create Date: 2025-06-29 00:50:49.396532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4e9dafa494'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index('ix_message_recipient_id')
        batch_op.drop_index('ix_message_sender_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('payload_json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index('ix_notification_user_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_post_user_id')
        batch_op.drop_column('language')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_task_name')
        batch_op.create_index(batch_op.f('ix_task_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('complete')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('complete', sa.BOOLEAN(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_task_timestamp'))
        batch_op.create_index('ix_task_name', ['name'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('completed')
        batch_op.drop_column('text')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.VARCHAR(length=5), nullable=True))
        batch_op.create_index('ix_post_user_id', ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_id', ['user_id'], unique=False)
        batch_op.alter_column('payload_json',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('ix_message_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('ix_message_recipient_id', ['recipient_id'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('followed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('follower_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
