"""Create Receipt table

Revision ID: b41e591b888e
Revises: 7f4e9dafa494
Create Date: 2025-06-29 02:09:55.937804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41e591b888e'
down_revision = '7f4e9dafa494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('gtq_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('usd_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('receipt_file', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt')
    # ### end Alembic commands ###
